Feature/recent post
orlantquijada/felicity-marketing-site pull request #23
Opened 2021-08-29 04:50 UTC by ayaendo

2021-08-30 09:33 UTC, orlantquijada requested changes

2021-08-30 09:33 UTC, orlantquijada commented on components/RecentPost/RecentCard.tsx
> +    >
i-separate lng ni ang container aya like `RecentPostsSection` sguro para ang `RecentCard` nga component reusable ra gyapon siya sa blogs list na nga page

2021-08-30 09:33 UTC, orlantquijada commented on components/RecentPost/RecentCard.tsx
> +        as={View}
no need nman sguro ning `as={View}` aya

2021-08-30 09:33 UTC, orlantquijada commented on components/RecentPost/RecentCard.tsx
> +export default function RecentCard() {
murag kuwang ni ug prop aya nga mo purma sa layout nga opposite ba like 

image | content -> content | image

currently sa imong implementation kay css grid pero i think better if flexbox imo gamiton kay para maka `row-reverse`

2021-08-30 09:33 UTC, orlantquijada commented on components/RecentPost/RecentCard.tsx
> +})
murag nice sguro aya if mag set kag wrapper sa image nga probably ang aspect ratio kay `1:1` gani if desktop nya if mobile na siya kay mo stretch lng siya sa container, nya para di ma stretch ang images kay i-`objectFit: cover` lng siya **note**: naa puy object fit nga prop ang next image https://nextjs.org/docs/api-reference/next/image#layout

if naa ka questions ani kay chat lnggg para mas maka explain pa pajd ko

2021-08-30 09:33 UTC, orlantquijada commented on components/RecentPost/RecentCard.tsx
> +})
pwede ni nimo gamiton as sample ayyy

https://v1.tailwindcss.com/components/cards#horizontal

2021-08-31 09:25 UTC, orlantquijada approved these changes

2021-08-31 11:47 UTC, orlantquijada requested changes

2021-08-31 11:47 UTC, orlantquijada commented on pages/index.tsx
> +      <Grid
murag pwede rani ma remove ang `Grid` aya nya ibutang lng ang css sa `View` babaw nya pwede rapd ma remove ang `position` mn sguro pd

2021-08-31 11:47 UTC, orlantquijada commented on components/Landing/Hero.tsx
> +      css={{ flexGrow: 1, position: 'relative', backgroundColor: '$white1' }}
murag pwede rapd ma remove ang `position` ari ayaaa

2021-08-31 12:04 UTC, ayaendo commented on pages/index.tsx
> +      <Grid
oo ako gitry ug remove ba pero ma in ani iya purma  naay gap sa kilidd unsaon ni haha
![image](https://user-images.githubusercontent.com/79971597/131499289-380b22af-5a55-4804-8aec-29fb1a3bb356.png)

2021-08-31 13:04 UTC, ayaendo commented on pages/index.tsx
> +      <Grid
if e remove ang Grid

2021-08-31 13:06 UTC, orlantquijada commented on pages/index.tsx
> +      <Grid
nya same ra siya maski imo na gi saka sa `View` ang css prop?

2021-08-31 14:13 UTC, orlantquijada approved these changes
nice kaaaa :100:

2021-08-31 14:14 UTC, merged