Feature/shop
orlantquijada/felicity-marketing-site pull request #32
Opened 2021-09-02 13:38 UTC by ayaendo

ignore lang sa input field, temporary sa na hahaha

then nag problema ko sa mga height kay welp ma scroll jud siya

2021-09-02 14:22 UTC, orlantquijada requested changes

2021-09-02 14:22 UTC, orlantquijada commented on components/Shop/shop.tsx
> +          gridTemplateAreas: ' "carousel" "content"',
need nig `gridTemplateRows: auto 1fr` para mag tupad siya pirme  like di mo stretch

2021-09-02 14:22 UTC, orlantquijada commented on components/Shop/shop.tsx
> +            gridTemplateColumns: '780px 1fr',
mas nice sguro aya if i-replace nimog responsive value ang `780px` para mo adjust ra siya depende sa size sa screen ako nasuwayan nga nindot nga value kay `50vw` pero best if ikaw mag try2 unsa nga values ang nice sa imo screen

2021-09-24 05:59 UTC, ayaendo commented
d ko sure sa handle submit hahahaha same ra ba ang notify sa subscribe? also dili mu work ang router?

2021-09-24 06:32 UTC, ayaendo commented
di ko sure sa handle submit if same ra ang subscribe ug notify? hahaha nya naay erorr sdd d ko kaybaw mu fix huhus

2021-09-24 09:58 UTC, ayaendo commented
btw dili ko sure sa handle submitt hahah pareha ra ba ang subsrcibe ug notify?

2021-09-24 10:16 UTC, orlantquijada commented
> btw dili ko sure sa handle submitt hahah pareha ra ba ang subsrcibe ug notify?

ako gi lahi ayaaa, ang subscribers kay para sa blog ra nya ang notify kay launch subscribers sila hahahaha anyway same ra sila ug body nga needed, ang endpoint lng ang lahi kay `/launch-subscribers` pwede ramn gani sguro nimo ma copy paste ang code nya change lng endpoint hahahaha
https://shielded-anchorage-15116.herokuapp.com/documentation/v1.0.0#/Launch-subscriber/post_launch_subscribers

2021-09-24 10:27 UTC, orlantquijada requested changes

2021-09-24 10:27 UTC, orlantquijada commented on components/Shop/shop.tsx
> +        <Link href="http://facebok.com" target="_blank">
please ko link ani sa felicity na ayaaa here ang link
https://play.google.com/store/apps/details?id=com.felicityincorporated.felicity

2021-09-24 10:27 UTC, orlantquijada commented on components/Shop/shop.tsx
> +        <Link href="http://facebok.com" target="_blank">
also please ko add ani na prop ayaaa for security ni `rel="noreferrer noopener"`
```suggestion
        <Link href="http://facebok.com" target="_blank" rel="noreferrer noopener">
```

2021-09-24 13:46 UTC, orlantquijada approved these changes

2021-09-24 13:46 UTC, merged